amaryllis/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls')),
]

app/urls.py
from django.conf.urls import url
from django.views.static import serve
from django.conf import settings
from . import views,upload

app_name= 'app'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^archive/$', views.archive, name='archive'),
    url(r'^category/$', views.category, name='category'),
    url(r'^article/$', views.article, name='article'),
    url(r'^tag/$', views.tag, name='tag'),
    url(r'uploads/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/upload/(?P<dir_name>[^/]+)$', upload.upload_image, name='upload_image'),
]

app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from collections import Counter
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

#标签模型
class Tag(models.Model):
    name = models.CharField(max_length=30,verbose_name="标签名称")

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.name


#分类模型
class Category(models.Model):
    name = models.CharField(max_length=30,verbose_name="分类名称")
    index = models.IntegerField(default=999,verbose_name="分类排序")

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['index','id']

    def __str__(self):
        return self.name

#文章model管理器
#进行文章按月归档，并统计每月文章数量
class ArticleManager(models.Manager):
    def data_article(self):
        article_date_publish = []
        article_archive_list = {}
        date_list = self.values('date_publish')
        for date in date_list:
            date = date['date_publish'].strftime('%Y%m')
            article_date_publish.append(date)

        article_archive_list = dict(Counter(article_date_publish))
        return article_archive_list

#w文章模型
class Article(models.Model):
    title = models.CharField(max_length=50,verbose_name="文章标题")
    desc = models.CharField(max_length=50,verbose_name="文章描述")
    content = models.TextField(verbose_name="文章内容")
    click_count = models.IntegerField(default=0,verbose_name="点击次数")
    is_recommend = models.BooleanField(default=False,verbose_name="是否推荐")
    date_publish = models.DateTimeField(auto_now_add=True,verbose_name="发布时间")#
#    user = models.ForeignKey(User,verbose_name="用户")
    category = models.ForeignKey(Category,blank=True,null=True,verbose_name="分类")
    tag = models.ManyToManyField(Tag,verbose_name="标签")

    objects = ArticleManager()

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    def add_click(self):
        self.click_count +=1
        self.save(update_fields=['click_count'])

    def __str__(self):
        return self.title

#友情链接
class Links(models.Model):
    title = models.CharField(max_length=50,verbose_name="标题")
    desc = models.CharField(max_length=200,verbose_name="友情链接描述")
    callback_url = models.URLField(verbose_name="url地址")
    date_publish = models.DateTimeField(auto_now_add=True,verbose_name="发布时间")
    index = models.IntegerField(default=999,verbose_name="排序")

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['index','id']

    def __str__(self):
        return self.title

#广告
class Ad(models.Model):
    title = models.CharField(max_length=50,verbose_name="广告标题")
    desc = models.CharField(max_length=200,verbose_name="广告描述")
    image_url = models.ImageField(upload_to="ad/%Y/%m",verbose_name="图片路径")
    callback_url = models.URLField(null=True,blank=True,verbose_name="回调URL")
    date_publish = models.DateTimeField(auto_now_add=True,verbose_name="发布时间")
    index = models.IntegerField(default=999,verbose_name="排序")

    class Meta:
        verbose_name = '广告'
        verbose_name_plural = verbose_name
        ordering = ['index', 'id']

    def __str__(self):
        return self.title

'''
#用户模型
class User(models.Model):
    avatar = models.ImageField(upload_to='avatar/%Y/%m', default='avatar/default.png', max_length=200, blank=True, null=True, verbose_name='用户头像')
    qq = models.CharField(max_length=20, blank=True, null=True, verbose_name='QQ号码')
    mobile = models.CharField(max_length=11, blank=True, null=True, unique=True, verbose_name='手机号码')
    url = models.URLField(max_length=100, blank=True, null=True, verbose_name='个人网页地址')

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.username


#评论模型
class Comment(models.Model):
    content = models.TextField(verbose_name='评论内容')
    username = models.CharField(max_length=30, blank=True, null=True, verbose_name='用户名')
    email = models.EmailField(max_length=50, blank=True, null=True, verbose_name='邮箱地址')
    url = models.URLField(max_length=100, blank=True, null=True, verbose_name='个人网页地址')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    user = models.ForeignKey(User, blank=True, null=True, verbose_name='用户')
    article = models.ForeignKey(Article, blank=True, null=True, verbose_name='文章')
    pid = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论')

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.id)
'''

app/templates/app/ad.html
    <div class="banner">
      <div id="slide-holder">
        <div id="slide-runner"> <a href="/" target="_blank"><img id="slide-img-1" src='../../static/images/a1.jpg' alt="" /></a> <a href="/" target="_blank"><img id="slide-img-2" src='../../static/images/a2.jpg' alt="" /></a> <a href="/" target="_blank"><img id="slide-img-3" src='../../static/images/a3.jpg' alt="" /></a> <a href="/" target="_blank"><img id="slide-img-4" src='../../static/images/a4.jpg' alt="" /></a>
          <div id="slide-controls">
            <p id="slide-client" class="text"><strong></strong><span></span></p>
            <p id="slide-desc" class="text"></p>
            <p id="slide-nav"></p>
          </div>
        </div>
      </div>

    <script>
        if(!window.slider) {
            var slider={};
        }

        slider.data= [
        {
            "id":"slide-img-1", // 与slide-runner中的img标签id对应
            "client":"",
            "desc":"" //这里修改描述
        },
        {
            "id":"slide-img-2",
            "client":"",
            "desc":""
        },
        {
            "id":"slide-img-3",
            "client":"",
            "desc":""
        },
        {
            "id":"slide-img-4",
            "client":"",
            "desc":"",
        }
        ];
    </script>
    </div>

app/templates/app/archive.html
{% extends 'app/base.html' %}
{% load staticfiles %}

{% block left_content %}
    {% include 'app/ad.html' %}
    <div class="topnews">
      <h2>{{ request.GET.year }}{{ request.GET.month }}归档文章</h2>
        {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="{% url 'app:article' %}?id={{ article.id }}">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l"><a href="/">{{ article.category.name }}</a></span><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a></span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><!--<span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">30</a>）</span>--></p>
        </ul>
      </div>
    {% endfor %}
    </div>

    {% include 'app/pagination.html' %}

{% endblock %}

app/templates/app/article.html
{% extends 'app/base.html' %}
{% load staticfiles %}
{% load myfilter %}

{% block left_content %}
    <div class="postdate">
        <div class="month">{{ article.date_publish | month_to_upper }}</div>
        <div class="date">{{ article.date_publish | date:'d' }}</div>
    </div>
    <div class="title">
        <h2><a href="" rel="bookmark" title="{{ article.title }}">{{ article.title }}</a></h2>
        <div class="postmeta">
          <span class="postmeta_author">{{ article.user.username }}</span>
          <span class="postmeta_category"><a href="" rel="category">{{ article.category.name }}</a></span>
          <span class="postmeta_time">{{ article.date_publish | date:'Y-m-d' }}</span>
        </div>
    </div>
        <div class="entry">
          {{ article.content | safe }}
        </div>
        <span class="tags">
            {% for tag in article.tag.all %}
            <a href="?tag={{ tag.name }}" rel="tag">{{ tag.name }}</a>
            {% endfor %}
        </span>
        <div class="info">
        【注】原创文章转载请说明出处，非常感谢!本文地址:  <a href="{{ SITE_URL }}article/?id={{ article.id }}" rel="bookmark" title="{{ article.title }}">{{ SITE_URL }}article/?id={{ article.id }}</a>
        </div>
{% endblock %}

app/templates/app/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{{ SITE_TITLE }}</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<link href="{% static 'css/index.css' %}" rel="stylesheet">
    {% block custom_css %} {% endblock %}
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/sliders.js' %}"></script>
<!--[if lt IE 9]>
  <script src="{% static 'js/modernizr.js' %}"></script>
  <![endif]-->
    {% block custom_js %} {% endblock %}
</head>
<body>
<header>
  <div class="logo">
      <h1>{{ SITE_NAME }}</h1>
      <p>{{ SITE_DESC }}</p>
      <!--<p>梦虽虚幻,却是自己的梦想；位虽低微,却是自己的岗位；屋虽简陋,却是自己的家；志虽渺小,却是自己的追求。</p>-->
  </div>
  <nav id="topnav" class="f_r">
    <ul>
      <a href="/">首页</a>
        {% for category in category_list %}
      <a href="{% url 'app:category' %}?cid={{ category.id }}">{{ category }}</a>
        {% endfor %}
    </ul>
    <script src="{% static 'js/nav.js' %}"></script>
  </nav>
</header>

<article>
    <div class="l_box f_l">
    {% block left_content %} {% endblock %}
    </div>
    <div class="r_box f_r">
      <div class="tit01">
      <h3>关注我[微信]</h3>
      <div class="gzwm">
          <img class="weixin2" src='../../static/images/weixin.png' alt="" />
          <!--
        <ul>
          <li><a class="wx" href="mailto:997876734@qq.com">邮箱</a></li>
          <li><a class="xlwb" href="#" target="_blank">新浪微博</a></li>
          <li><a class="txwb" href="#" target="_blank">腾讯微博</a></li>
          <li><a class="rss" href="portal.php?mod=rss" target="_blank">RSS</a></li>
        </ul>
        -->
      </div>
    </div>
    <!--tit01 end-->
    <div class="moreSelect" id="lp_right_select">
      <script>
        window.onload = function ()
        {
            var oLi = document.getElementById("tab").getElementsByTagName("li");
            var oUl = document.getElementById("ms-main").getElementsByTagName("div");

            for(var i = 0; i < oLi.length; i++)
            {
                oLi[i].index = i;
                oLi[i].onmouseover = function ()
                {
                    for(var n = 0; n < oLi.length; n++) oLi[n].className="";
                    this.className = "cur";
                    for(var n = 0; n < oUl.length; n++) oUl[n].style.display = "none";
                    oUl[this.index].style.display = "block"
                }
            }
        }
      </script>
      <div class="ms-top">
        <ul class="hd" id="tab">
          <li class="cur"><a href="/">浏览排行</a></li>
          <!--<li><a href="/">评论排行</a></li>-->
          <li><a href="/">站长推荐</a></li>
        </ul>
      </div>
      <div class="ms-main" id="ms-main">
        <div style="display: block;" class="bd bd-news" >
          <ul>
              {% for click_article in click_article_list %}
            <li><a href="{% url 'app:article' %}?id={{ click_article.id }}" target="_blank">{{ click_article.title }}</a></li>
              {% endfor %}
          </ul>
        </div>
          <!--
        <div  class="bd bd-news">
          <ul>
            <li><a href="/" target="_blank">原来以为，一个人的勇敢是，删掉他的手机号码...</a></li>
            <li><a href="/" target="_blank">手机的16个惊人小秘密，据说99.999%的人都不知</a></li>
            <li><a href="/" target="_blank">住在手机里的朋友</a></li>
            <li><a href="/" target="_blank">教你怎样用欠费手机拨打电话</a></li>
            <li><a href="/" target="_blank">你面对的是生活而不是手机</a></li>
            <li><a href="/" target="_blank">豪雅手机正式发布! 在法国全手工打造的奢侈品</a></li>
          </ul>
        </div>
        -->
        <div class="bd bd-news">
          <ul>
              {% for recommend_article in recommend_article_list %}
                    <li><a href="{% url 'app:article' %}?id={{ recommend_article.id }}" target="_blank">{{ recommend_article.title }}</a></li>
              {% endfor %}
          </ul>
        </div>
      </div>
      <!--ms-main end -->
    </div>
    <div class="tuwen">
      <h3>文章归档</h3>
      <ul>
          {% for key,value in archive_list.items %}
        <li>
          <p><span class="tutime font-size-18"><a href="{% url 'app:archive' %}?year={{ key | slice:':4' }}&month={{ key | slice:'4:7' }}">{{ key }}文章归档({{ value }})</a></span></p>
        </li>
          {% endfor %}
      </ul>
    </div>
    <div class="cloud">
      <h3>标签云</h3>
      <ul>
          {% for tag in tag_list %}
        <li><a href="{% url 'app:tag' %}?tid={{ tag.id }}">{{ tag }}</a></li>
          {% endfor %}
      </ul>
    </div>
    <div class="links">
      <h3>友情链接</h3>
      <ul>
          {% for link in links_list %}
        <li><a href="{{ link.callback_url }}">{{ link.title }}</a></li>
          {% endfor %}
      </ul>
    </div>
    </div>
  <!--r_box end -->
</article>

<footer>
  <p class="ft-copyright">{{ SITE_NAME }}的个人站点 渝ICP备736382822号-1</p>
  <div id="tbox"> <a id="togbook" href="/"></a> <a id="gotop" href="javascript:void(0)"></a> </div>
</footer>
</body>
</html>

app/templates/app/category.html
{% extends 'app/base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'app/ad.html' %}
    <div class="topnews">
      <h2>{{ category.name }}</h2>
      {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="{% url 'app:article' %}?id={{ article.id }}">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><!--<span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span>--></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'app/pagination.html' %}
{% endblock %}

app/templates/app/failure.html
{% extends 'app/base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'app/ad.html' %}
    <div class="topnews">
      <h2>{{ reason }}</h2>
    </div>
    {% include 'app/pagination.html' %}
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load staticfiles %}

{% block left_content %}
    {% include 'app/ad.html' %}
    <div class="topnews">
      <h2>最新文章</h2>
        {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="{% url 'app:article' %}?id={{ article.id }}">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a></span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><!--<span class="pingl f_r">评论（<a href="/">0</a>）</span>--></p>
        </ul>
      </div>
    {% endfor %}
    </div>


    {% include 'app/pagination.html' %}

{% endblock %}

app/templates/app/pagination.html
<div id="pagination">
    <ul id="pagination-flickr">
    {% if article_list.has_previous %}
    <li class="previous"><a href="?page={{ article_list.previous_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}{% if request.GET.cid %}&cid={{ request.GET.cid }}{% endif %}">&laquo;上一页</a></li>
    {% else %}
    <li class="previous-off">&laquo;上一页</li>
    {% endif %}

     <li class="active">{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li>

    {% if article_list.has_next %}
      <li class="next"><a href="?page={{ article_list.next_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}{% if request.GET.cid %}&cid={{ request.GET.cid }}{% endif %}">下一页 &raquo;</a></li>
    {% else %}
      <li class="next-off">下一页 &raquo;</li>
    {% endif %}
   </ul>
</div>

app/templates/app/tag.html
{% extends 'app/base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'app/ad.html' %}
    <div class="topnews">
      <h2>{{ tag.name }}</h2>
      {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="{% url 'app:article' %}?id={{ article.id }}">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><!--<span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span>--></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'app/pagination.html' %}
{% endblock %}